spring:
  jpa:
    hibernate:
    ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL55Dialect
    generate-ddl: true
  redis:
     host: 127.0.0.1
     port: 6379
     database: 10
     timeout: 2500
  datasource:
    username: root
    password: wxy987wxy
    url: jdbc:mysql://127.0.0.1:3306/auth?characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    enabled: true
    serviceUrl: #注册中心的注册地址
      defaultZone: http://127.0.0.1:8888/eureka/
server:
  port: 8763  #服务端口号



